### ISSUE TITLE
[BUG] Icons and colors not showing in calendar mode

### ISSUE THREAD

**Issue by jel80** [marksie1988/atomic_calendar_revive#46]
**Describe the bug**
Calendar is not showing color or icons on the monthly Calendar glance view. Does correctly show in Events view.

**To Reproduce**
Inside my ui-lovelace.yaml file:
` resources:
  - url: /local/community_plugin/atomic_calendar_revive/atomic-calendar-revive.js
    type: module

title: Home
views:
  - icon: mdi:calendar
    title: Calendars
    cards:
      - type: "custom:atomic-calendar-revive"
        name: "Calendar"
        enableModeChange: true
        showColors: true
        defaultMode: 2
        firstDayOfWeek: 7
        maxDaysToShow: 10
        entities:
          - type: holiday
            titleColor: red
            entity: calendar.holidays_in_united_states
          - type: icon1
            entity: calendar.family`

**Expected behavior**
Expected to see color and icon updates on the Calendar view (defaultMode: 2)

**Screenshots**
![Screen Shot 2020-04-04 at 8 46 11 AM](https://user-images.githubusercontent.com/21181026/78455032-d28ae280-7650-11ea-862f-9f7bdd8f1022.png)
![Screen Shot 2020-04-04 at 8 47 02 AM](https://user-images.githubusercontent.com/21181026/78455051-f3533800-7650-11ea-996b-276f675fd54e.png)

**Setup Information (please complete the following information):**
I have tried on both Chrome and Firefox on a Mac. Cleaned out cache/cookies as well. 
Newest js file as it was git cloned down this morning (4/4/20)

**Additional context**

**Comment by marksie1988** [comment]
Thanks for logging this, I have now found the issue which is related to the Whitelist feature that was added. 

I'm currently working on a fix for this.

**Comment by jel80** [comment]
Awesome, thanks!
